### PR TITLE
Always track visits

### PR DESCRIPTION
**Pull request by chischaschos**
- Remove Ahoy::Tracker#check_for_persistance behavior, it can be
  implemented via a custom store
- Always track visits, let store decide what to do with them.

### CODE REVIEW

**Comment by icco** [comment]
So this implies to me that we can bring ahoy back inline with the ahoy main branch. Thoughts?

**Comment by icco** [comment]
cc @tomfbiz

**Comment by chischaschos** [comment]
@icco more or less, because we have https://github.com/littlebitselectronics/ahoy/pull/15/files#diff-c3f419f83b648ccfd096c914684a8f80R38 and https://github.com/littlebitselectronics/ahoy/pull/15/files#diff-35255b8e0bc32159dddd6985481e0770R32 which are not part of the main ahoy branch.

**Comment by icco** [comment]
Thanks. v1.1.1-littlebits is the version for before this. v1.2.0-littlebits is the new version.

**Comment by chischaschos** [comment]
yeii ty, will watch this carefully.

**Pull request merged**
